spring:
  jpa:
    database: postgresql
    driver-class-name: org.postgresql.Driver
  datasource:
    url: ${DATA_STORE_DB_URL:jdbc:postgresql://localhost:5050/ccd_data?stringtype=unspecified}
    username: ${DATA_STORE_DB_USERNAME:ccd}
    password: ${DATA_STORE_DB_PASSWORD:ccd}
event-list-file: ${EVENT_LIST_FILE:}
dry-run: ${DRY_RUN:false}
start-date: ${START-DATE:2021-02-02}
end-date: ${END-DATE:2023-02-05}